---

- name: Remove conflicting packages (e.g. podman, buildah)
  package:
    name:
      - podman
      - buildah
    state: absent

- name: Add Docker CE repositories
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    owner: root
    group: root
    mode: 0644

- name: Install Docker CE
  package:
    name: docker-ce
    state: present

- name: Enable und start docker
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Add user vagrant to group docker
  user:
    name: vagrant
    append: yes
    groups: docker

- name: Install minikube
  dnf:
    name: https://storage.googleapis.com/minikube/releases/latest/minikube-latest.x86_64.rpm
    disable_gpg_check: yes
    state: latest
