---

- name: Get VirtualBox version on guest VM
  shell: dmidecode | grep vboxVer | cut -b 20-
  register: cmd
  changed_when: false

- name: Save VirtualBox version for further processing
  set_fact:
    vbox_version: "{{cmd.stdout}}"

- debug: msg="{{vbox_version}}"

- name: Get version of VirtualBox guest additions
  shell: modinfo vboxguest
  register: vboxguest_addons
  changed_when: false
  ignore_errors: yes

- debug:
    msg: "RC 'modinfo vboxguest': {{vboxguest_addons.rc}}"
