---

- name: Install git
  package:
    name: git
    state: present

- name: Set git user.name for root
  git_config:
    name: user.name
    scope: global
    value: "{{ git_config_user_name }}"

- name: Set git user.email for root
  git_config:
    name: user.email
    scope: global
    value: "{{ git_config_user_email }}"
